services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gynnota-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd}", "-C", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: ../backend
      dockerfile: src/GynNota.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=db,1433;Database=GynNota;User Id=sa;Password=${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd};TrustServerCertificate=True;
      - CRYPTO_KEY=${CRYPTO_KEY:-dev-insecure-key-change}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  sqlserver_data:
